# Generated by Django 4.1.2 on 2022-10-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_Name', models.CharField(max_length=200)),
                ('city_Name', models.CharField(max_length=200)),
                ('tenderOrder', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.state')),
            ],
        ),
    ]
