# Generated by Django 4.1.2 on 2022-10-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='tenderName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tender Name'),
        ),
        migrations.AlterField(
            model_name='state',
            name='city_Name',
            field=models.CharField(blank=True, max_length=200, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_Name',
            field=models.CharField(blank=True, max_length=200, verbose_name='State Name'),
        ),
        migrations.AlterField(
            model_name='state',
            name='tenderOrder',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tender Order ID'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tenderID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.state', verbose_name='Tender ID'),
        ),
    ]
