# Generated by Django 4.1.2 on 2022-10-22 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_tender_tendername_alter_state_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='state',
            name='status',
            field=models.BooleanField(default=1, editable=False),
        ),
    ]
