# Generated by Django 4.1.2 on 2022-10-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_state_created_on_alter_state_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='state',
            name='status',
        ),
    ]
