# Generated by Django 4.1.2 on 2022-10-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_state_created_on_remove_state_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Tender Name')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('query', models.CharField(blank=True, max_length=200, verbose_name='Query Description')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Phone')),
            ],
        ),
    ]
